In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [16]:
# Define the Vocabulary Size
voc_size=10000

In [24]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [18]:
## One Hot Representation
one_hot_Rep=[one_hot(words,voc_size)for words in sent]
one_hot_Rep

[[6091, 7821, 5899, 9682],
 [6091, 7821, 5899, 1672],
 [6091, 8202, 5899, 7593],
 [9322, 2461, 792, 7306, 4625],
 [9322, 2461, 792, 7306, 3110],
 [3582, 6091, 8022, 5899, 4993],
 [7856, 8014, 1609, 7306]]

In [25]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [20]:
sent_length=8
embedded_docs=pad_sequences(one_hot_Rep,padding='pre',maxlen=sent_length)
print(embedded_docs)


[[   0    0    0    0 6091 7821 5899 9682]
 [   0    0    0    0 6091 7821 5899 1672]
 [   0    0    0    0 6091 8202 5899 7593]
 [   0    0    0 9322 2461  792 7306 4625]
 [   0    0    0 9322 2461  792 7306 3110]
 [   0    0    0 3582 6091 8022 5899 4993]
 [   0    0    0    0 7856 8014 1609 7306]]


In [21]:
# Feature Dimension
dim = 10

In [22]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [27]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 216ms/step


array([[[ 3.87630798e-02,  2.30189227e-02, -3.28050740e-02,
         -4.26522642e-03, -1.38066411e-02, -3.95362973e-02,
          2.54872777e-02,  2.88509168e-02, -4.33077589e-02,
          2.88121589e-02],
        [ 3.87630798e-02,  2.30189227e-02, -3.28050740e-02,
         -4.26522642e-03, -1.38066411e-02, -3.95362973e-02,
          2.54872777e-02,  2.88509168e-02, -4.33077589e-02,
          2.88121589e-02],
        [ 3.87630798e-02,  2.30189227e-02, -3.28050740e-02,
         -4.26522642e-03, -1.38066411e-02, -3.95362973e-02,
          2.54872777e-02,  2.88509168e-02, -4.33077589e-02,
          2.88121589e-02],
        [ 3.87630798e-02,  2.30189227e-02, -3.28050740e-02,
         -4.26522642e-03, -1.38066411e-02, -3.95362973e-02,
          2.54872777e-02,  2.88509168e-02, -4.33077589e-02,
          2.88121589e-02],
        [-1.21409893e-02, -9.17566940e-03, -3.99857163e-02,
          1.63792409e-02,  2.67478488e-02, -2.38201767e-03,
         -1.36238933e-02,  2.01927535e-02,  2.453197

In [28]:
embedded_docs[0]

array([   0,    0,    0,    0, 6091, 7821, 5899, 9682], dtype=int32)

In [36]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


array([[ 0.03876308,  0.02301892, -0.03280507, -0.00426523, -0.01380664,
        -0.0395363 ,  0.02548728,  0.02885092, -0.04330776,  0.02881216],
       [ 0.03876308,  0.02301892, -0.03280507, -0.00426523, -0.01380664,
        -0.0395363 ,  0.02548728,  0.02885092, -0.04330776,  0.02881216],
       [ 0.03876308,  0.02301892, -0.03280507, -0.00426523, -0.01380664,
        -0.0395363 ,  0.02548728,  0.02885092, -0.04330776,  0.02881216],
       [ 0.03876308,  0.02301892, -0.03280507, -0.00426523, -0.01380664,
        -0.0395363 ,  0.02548728,  0.02885092, -0.04330776,  0.02881216],
       [-0.01214099, -0.00917567, -0.03998572,  0.01637924,  0.02674785,
        -0.00238202, -0.01362389,  0.02019275,  0.02453197, -0.03886356],
       [ 0.02872277,  0.00483332,  0.0314267 ,  0.02690757, -0.02281057,
         0.02630181,  0.01664056,  0.00182762,  0.04526665,  0.04846174],
       [ 0.01366576,  0.0356964 , -0.00912767,  0.00341765, -0.00865237,
        -0.01226024, -0.03019807,  0.02617648